/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package autonoma.PulgasLocas.views;

import autonoma.PulgasLocas.models.PanelJuego;
import autonoma.PulgasLocas.models.SimuladorPulgas;
import java.awt.BorderLayout;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author marib
 */
public class VentanaPrincipal extends JFrame {
    private PanelJuego panelJuego;
    private JLabel lblPuntaje;
    private JLabel lblPuntajeMaximo;

    public VentanaPrincipal() {
        panelJuego = new PanelJuego(new SimuladorPulgas());
        lblPuntaje = new JLabel("Puntaje: 0");
        lblPuntajeMaximo = new JLabel("Máximo: 0");

        // Configuración básica del JFrame
        setTitle("Simulador de Pulgas");
        setLayout(new BorderLayout());
        add(lblPuntaje, BorderLayout.NORTH);
        add(panelJuego, BorderLayout.CENTER);
        add(lblPuntajeMaximo, BorderLayout.SOUTH);
        pack();
        setVisible(true);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    public void actualizarPuntaje(int puntaje) {
        lblPuntaje.setText("Puntaje: " + puntaje);
    }

    public void actualizarPuntajeMaximo(int puntajeMaximo) {
        lblPuntajeMaximo.setText("Máximo: " + puntajeMaximo);
    }

    public void mostrarDialogoFinJuego(int puntajeFinal) {
        JOptionPane.showMessageDialog(this, "¡Juego terminado!\nPuntaje: " + puntajeFinal);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
